# Generated by Django 5.2.7 on 2025-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_courserating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='detail',
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='teacher_profile_imgs/'),
        ),
    ]
