# Generated by Django 5.2.7 on 2025-11-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_courserating_options_studentfavoritecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '8. Course Rating'},
        ),
    ]
