# Generated by Django 5.2.7 on 2025-11-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_studentassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name_plural': '9. Student Assignments'},
        ),
    ]
