# Generated by Django 5.2.7 on 2025-11-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_notification_notif_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notif_read_status',
            new_name='notifiread_status',
        ),
    ]
