# Generated by Django 5.2.7 on 2025-11-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_notif_read_status_notification_notifiread_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='student_status',
            field=models.BooleanField(default=False),
        ),
    ]
