# Generated by Django 5.2.7 on 2025-11-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_attempquiz_right_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
    ]
